// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jccypihclafrnahsligl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjY3lwaWhjbGFmcm5haHNsaWdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NTQxOTAsImV4cCI6MjA3MjMzMDE5MH0.JZo7iLOI9Dfw4OdilgMRYA0DQ6zEVdFuiP3SeO4JtVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});